version: "3.9"
services:
    contracts-app:
        build: .
        command: sh -c "npx sequelize-cli db:migrate && node dist/server.js"
        ports:
            - "3000:3000"
        env_file:
            - .env
        environment:
            - DB_HOST=postgres
        depends_on:
            - postgres

    postgres:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_DB: hometask
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
