version: "3.9"
services:
    # food-kart-app:
    #     container_name: food-kart-backend
    #     build: .
    #     command: sh -c "npx sequelize-cli db:migrate && node dist/server.js"
    #     ports:
    #         - "3000:3000"
    #     env_file:
    #         - .env
    #     environment:
    #         - DB_HOST=postgres
    #     depends_on:
    #         - postgres
    #         - redis

    postgres:
        image: postgres:16
        container_name: food_kart_pg
        restart: always
        environment:
            POSTGRES_DB: food_kart
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pg_data:/var/lib/postgresql/data

    redis:
        image: redis:7
        container_name: food_kart_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
volumes:
    pg_data:
    redis_data:
